<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1330" started-at="2020-07-04T08:16:37Z" finished-at="2020-07-04T08:16:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1330" started-at="2020-07-04T08:16:37Z" finished-at="2020-07-04T08:16:38Z">
      <class name="module9.TestCase.HashMapdata">
        <test-method status="FAIL" signature="Test(java.util.Map)[pri:0, instance:module9.TestCase.HashMapdata@4f933fd1]" name="Test" duration-ms="1299" started-at="2020-07-04T13:46:37Z" data-provider="testdata" finished-at="2020-07-04T13:46:38Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: Test([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap){UserName=user1, DoB=dob1, Password=pass1},null,null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: Test([Parameter{index=0, type=java.util.Map, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap){UserName=user1, DoB=dob1, Password=pass1},null,null]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test -->
      </class> <!-- module9.TestCase.HashMapdata -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
